# _config.yml based on nipreps/qc-book
# https://github.com/nipreps/qc-book/blob/26b183531511083bd50ff2e66dffce5a9baef788/docs/_config.yml

title: "Dandisets Book"
author: "The Dandisets Book Authors"

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Sphinx customizations
sphinx:
  config:
    nb_custom_formats:
      .Rmd:
        - jupytext.reads
        - fmt: Rmd
    bibtex_reference_style: author_year
    # html_extra_path: ["assets"]
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# Execution settings
execute:
  timeout: 3000
  exclude_patterns:
    - 0*ipynb
  execute_notebooks: auto

# HTML-specific settings
html:
  use_repository_button: true
  # use_issues_button: true
  use_edit_page_button: false
  home_page_in_navbar: true

# Launch button settings
launch_buttons:
  notebook_interface: "jupyterlab"
  jupyterhub_url: "https://hub.dandiarchive.org"
  binderhub_url: "https://mybinder.org"

repository:
  url: https://github.com/dandi/dandisets-book
  path_to_book: docs
  branch: master

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution